changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - refactor
        - ci
        - chore
        - documentation
    - title: Other Changes
      labels:
        - "*"
